name = "Infinity Plus"
author = "cassiancc"
version = "1.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ecdf689b456e00d181b68455210112a1db8be218aa352eb94f767c106f0f9b33"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
