name = "Infinity Plus"
author = "cassiancc"
version = "2.3.8.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22df9085781562359df76faf2b65c101013286283e13dfe647a14fd2a946a413"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
