name = "Simply Vanilla 1.20.1"
author = "cassiancc"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "229a9a802695b9adea4f9adf1fb10aeddf3fa411925aea6313abac141ebea809"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
