name = "Infinity Plus"
author = "cassiancc"
version = "1.10.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2daa365be1d9b17eadc10b73ae12ee5980ae03ef6ece42d47012a3c3d27aa4fa"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
