name = "Infinity Plus"
author = "cassiancc"
version = "2.3.8.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a331764448d00d8a7a9898b5e2230c88b9f880ce50e28c2e81d56d33ac953e4f"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
