name = "Infinity Plus"
author = "cassiancc"
version = "1.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d23506e01c879df61c3d6088c9514bac8b2ad1a09588e80c125770a2c9716871"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
