name = "Infinity Plus"
author = "cassiancc"
version = "1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eaef92e5f7a1a789d7bcb909ac184c22b4ec993667b32403a3c507303fb38173"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
