name = "Simply Vanilla 1.20.1"
author = "cassiancc"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ecaf5b885882b9d2213adf367f470138060b67b4adc873831d33c3c1fa8dbc82"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
