name = "Infinity Plus"
author = "cassiancc"
version = "1.10.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ac0b5f73111fc31e8b1070a2936f1833f2f0ce1513314b056602ed4062878cc"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
