name = "Infinity Plus"
author = "cassiancc"
version = "1.10.8.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b87925051db58bdfb66418fecb0f3ed02268dbe33730faed09191f34b6399d3e"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
