name = "Infinity Plus"
author = "cassiancc"
version = "1.10.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b181b62012897ace9b8b43dc6283861eba894d580603c5ceb9fade42b8efa94e"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
