name = "Infinity Plus"
author = "cassiancc"
version = "1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4777621561cf8470f606fa0050700c0f472ce7a2cd51101e96d8a9ffaf1aba5c"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
