name = "Infinity Plus"
author = "cassiancc"
version = "1.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b489579da11b84d1184f848ed4bbab7f2b520fb3044de4787696955187c0a53"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
