name = "Infinity Plus"
author = "cassiancc"
version = "2.0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a977169b48618565e2d54891dcb2c4c2b70710a8e03e024ed460a370610b0cb4"

[versions]
fabric = "0.16.7"
minecraft = "1.21.1"
