name = "Infinity Plus"
author = "cassiancc"
version = "1.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60d1e5dc1194ebb692345fa4822ce0986621a3ee6dda442d9a46939aacf652ed"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
