name = "Infinity Plus"
author = "cassiancc"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f76151e0e5d5ada02236781213ddd8e11662b2d2cca27bc7c956a1cb25ac16c"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
