name = "Infinity Plus"
author = "cassiancc"
version = "1.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03633a528b5a9e3e5aa5d6cbbbf27649d7eefea858ec26690f4118d2bd7fd28e"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
