name = "Simply Vanilla 1.20.1"
author = "cassiancc"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2302857b2346fbae5fb704adbd36022faef8fc3e37ab1d11c487f97911784d1c"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
