name = "Simply Vanilla 1.20.1"
author = "cassiancc"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ae07f9c9c8de600edaea0ecc13bd4c9862cdb9770c2b4d649d3f99ce6c73c1c"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
