name = "Infinity Plus"
author = "cassiancc"
version = "1.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "617acc01d9e52395a288ff0168700aa3570c377ac8332725dac4cd8da687fafd"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
