name = "Infinity Plus"
author = "cassiancc"
version = "1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4172a74bf8a72800838eb36857f888a2915206a7851e413eb871c999001fa8f8"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
