name = "Infinity Plus"
author = "cassiancc"
version = "1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06451f7e07aa68a8a96892cd8fff618af56af5da162c3d8fcf3e63de7bdc9bcf"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
