name = "Infinity Plus"
author = "cassiancc"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64ce0936b7aca86d55fad4e880cd568e26c8d55b35b69a9651ad5db600b98807"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
