name = "Infinity Plus"
author = "cassiancc"
version = "1.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27d2a67d5189068695edd6af996214ab00e1a5be9facc5c8ef15d9e33c2e80d6"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
