name = "Infinity Plus"
author = "cassiancc"
version = "1.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d94decfff8631f18d56a75e743fb5fd86378a95fd4dd84c7dea0a03005f61e95"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
