name = "Simply Vanilla 1.20.1"
author = "cassiancc"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ca590a4e01998f5121bff6333e64805b03f40d1d55c25a56b11cf1d65f47a00"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
