name = "Infinity Plus"
author = "cassiancc"
version = "1.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "394fe4275f7a252bb017fd3a58b3e2056300b084cd8676bc6e84ff8d4538fb29"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
