name = "Infinity Plus"
author = "cassiancc"
version = "1.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8a4dc08c16423f96ceb1516aa8eb1f57ac93860428bd7ff6ffc6d5fe21ece8b"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
