name = "Infinity Plus"
author = "cassiancc"
version = "1.12.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ec5f367427acff8b469d92604a9d2215d99c62ca1dc70732f9ee434cbdfdfd0"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1", "1.21"]
