name = "Infinity Plus"
author = "cassiancc"
version = "1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ddefb647ab1592ea0f924b27f6b1be665c73d93a6b3341670af8e72522a7a386"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
